name: Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NIX_SIGNING_PRIVATE_KEY: local-cache-1:Ag+FcT4T15iUMQRpDvFlMr8l/jUOpuc7x6Bo2n0HYIc+syTOOXHisb/njnTQpwQQegagaW2MxsH4IqJFYYbfvQ==
      NIX_SIGNING_PUBLIC_KEY: local-cache-1:PrMkzjlx4rG/54500KcEEHoGoGltjMbB+CKiRWGG370=

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            extra-substituters = file://${{ runner.temp }}/nix-binary-cache
            extra-trusted-public-keys = ${{ env.NIX_SIGNING_PUBLIC_KEY }}
            post-build-hook = ${{ runner.temp }}/post-build.sh

      - name: Cache Nix
        uses: sgillespie/actions/basic-nix-cache@latest
        with:
          signing-private-key: ${{ env.NIX_SIGNING_PRIVATE_KEY }}
          path: ${{ runner.temp }}/nix-binary-cache
          key: ${{ runner.os }}-nix-cache

      - name: Build hello
        run: |
          nix build nixpkgs\#pkgsCross.musl64.hello
