
name: Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Nix
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/nix-binary-cache
          key: ${{ runner.os }}-nix-cache-sgillespie

      - name: Create Nix post build script
        run: |
          cat <<EOF > "${{ runner.temp }}/post-build.sh"
            #!/usr/bin/env bash
            set -eux
            set -f         # Disable globbing
            export IFS=' ' # Separate paths by space

            echo "Signing paths" $OUT_PATHS
            nix store sign --key-file nix-cache-secret.key --recursive $OUT_PATHS

            echo "Uploading paths" $OUT_PATHS
            nix copy --to "file://${{ runner.temp }}/nix-binary-cache" nixpkgs\#pkgsCross.musl64.hello
          EOF

          chmod +x "${{ runner.temp }}/post-build.sh"

          cat "${{ runner.temp }}/post-build.sh"

          ${{ runner.temp }}/post-build.sh

      - name: Prepopulate Nix Cache
        run: |
          mkdir -p "${{ runner.temp }}/nix-binary-cache/nar"

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            extra-substituters = file://${{ runner.temp }}/nix-binary-cache
            extra-trusted-public-keys = local-cache-1:PrMkzjlx4rG/54500KcEEHoGoGltjMbB+CKiRWGG370=
            require-sigs = true
            post-build-hook = ${{ runner.temp }}/post-build.sh

      - name: Build hello
        run: |
          nix build -v nixpkgs\#pkgsCross.musl64.hello
